Docs/contributors  adding projects
OpenMined/docs pull request #35
Opened 2017-08-15 00:57 UTC by cereallarceny

Attempting to figure out how we may better guide users from "I want to help on this project" to actually joining a specific team or part of the OpenMined ecosystem.  How do we direct people where they need to go to start helping?... rather than assume they'll figure it out on their own by reading Slack.

See

2017-08-15 00:58 UTC, cereallarceny commented
I've gone ahead and filled out "Machine Learning" as a potential example... we'll want to document the others.

2017-08-15 13:58 UTC, kevinahuber commented
I would leave this out of the quickstart, and make it a link outside of it. I think its SUPER overwhelming to have the project as a whole, and the quickstart is like the tutorial level to OpenMined. You kill some skeletons, make a fire, do your first spell, _then_ receive a map from uncle Patrick upon completion.

2017-08-15 15:56 UTC, cereallarceny commented
Fair enough, that's not a bad idea.  Maybe treat it as a "token of accomplishment"?  The only problem I see with that is it requires people to have a knowledge of Python and machine learning.  Most front-end developers, much less designers, UX specialists, lawyers, and marketers will be able to get past that though.  I would be concerned that could be a massive bottleneck for less technical individuals.

2017-08-15 16:19 UTC, cereallarceny commented
@iamtrask I added the other sections in, but I'm not sure if I got all the right repos in the right place.  Can I get a quick copy check to make sure all the information is factual?  Also note, we don't have a sonar.js library so that's missing a link until further notice.

2017-08-15 19:50 UTC, cereallarceny commented
@swaroopch I implemented the changes to the Slack channel names as discussed.  Would you mind confirming this in my latest commit?

2017-08-16 01:15 UTC, swaroopch reviewed
LGTM!

2017-08-16 01:15 UTC, swaroopch commented on contributing/quickstart.md
> +- [Sonar](https://github.com/OpenMined/Sonar) - Python Eterheum blockchain implementation
typo - `s/Eterheum/Ethereum`

2017-08-16 01:15 UTC, swaroopch commented on contributing/quickstart.md
> +- [Sonar](https://github.com/OpenMined/Sonar) - Python Eterheum blockchain implementation
typo - s/Eterheum/Ethereum

2017-08-16 01:15 UTC, swaroopch commented on contributing/quickstart.md
> +- [sonar.js](NEEDS A LINK) - Node.js client to blockchain application (Sonar)
Remove the link for now?

2017-08-16 01:15 UTC, swaroopch commented on contributing/quickstart.md
> +**Slack channels:** #terminology, #process, #team_docs
Remove `#terminology` - no longer exists

2017-08-16 01:16 UTC, swaroopch commented on contributing/quickstart.md
> +**Repositories:** None
say "all" instead?

2017-08-16 01:18 UTC, swaroopch commented
@cereallarceny Do we want to mention `#beginner` and `#questions` channels?

2017-08-16 01:18 UTC, cereallarceny commented
Good idea, definitely.  Working on a commit for all these changes.

2017-08-16 01:20 UTC, cereallarceny commented
Approve the review and merge me in boss!

2017-08-16 01:48 UTC, swaroopch commented on contributing/quickstart.md
> +- [sonar.js (Link pending) - Node.js client to blockchain application (Sonar)
extra leading square bracket??

2017-08-16 01:48 UTC, swaroopch commented on contributing/quickstart.md
> +- [sonar.js (Link pending) - Node.js client to blockchain application (Sonar)
extra leading square bracket??

2017-08-16 01:49 UTC, swaroopch commented on contributing/quickstart.md
> +We'd love to have you! The only requirement for joining the OpenMined contributor network is a desire to follow the core values and vision of the project. Feel free to reach out in the #general, #beg
I believe it is called `#general-discussion` and not `#general`?

2017-08-16 01:50 UTC, swaroopch commented
> Approve the review and merge me in boss!

I can do that!? 😮

Just one blocking change - about `#general-discussion` (not `#general`) and we should be good to merge 🙂

2017-08-16 16:47 UTC, cereallarceny commented
Pushed up those changes, sir!  I think you can review it if you want.  We can't merge until a review has been approved.  :)

2017-08-16 17:57 UTC, swaroopch approved these changes

2017-08-16 17:58 UTC, swaroopch commented
@cereallarceny github says "At least one approved review is required by reviewers with write access." - I guess I don't have write access :)

2017-08-16 18:06 UTC, cereallarceny commented
Dang it!  @iamtrask We need your help!

2017-08-16 18:29 UTC, anoff approved these changes
me to the rescue \o/

2017-08-16 18:29 UTC, anoff commented on contributing/quickstart.md
> +
Step 3 is there twice. I assume the first one is legacy? :)

2017-08-16 18:29 UTC, anoff commented on contributing/quickstart.md
> +#### Node.js Development
Programming language and domain seem to be non-exclusive. Do you think putting the whole thing in a table would be possible?

for example:

| # | python | nodeJS | react |
|:----------------------:|----------------|--------------------|----------|
| blockchain | pySonar | mine.js capsule.js | - |
| homomorphic encryption | pySyft | capsule.js | - |
| UX | sonar notebook | adapters | sonar UI |

2017-08-16 18:29 UTC, anoff commented on contributing/quickstart.md
> +- [Capsule](https://github.com/OpenMined/Capsule) - Blockchain oracle for time released public/private key generation/interaction
it's gonna be `capsule.js` 👯

2017-08-16 20:27 UTC, iamtrask requested changes
I second the notion that this is very intimidating as a document. Step 3 should instead be the last step, and it should broken out into sub pages (sortof like the old Goosebumps books!...choose your own ending).

2017-08-17 01:39 UTC, cereallarceny commented
Why do we want to put these at the end @iamtrask?  What about for people who aren't technical or aren't Python developers?  I can't imagine them being very interested in spinning up Sonar if they have UI design expertise.  I think that narrows the scope of interested individuals significantly.  Maybe we should appeal to less technically savvy individuals as well?

2017-08-18 22:58 UTC, kevinahuber requested changes
@cereallarceny brings up a good point, but I don't think the answer is to put this part in the middle. 
This quickstart is best for particularly python developers and the first components we had code for. After Hydrogen, the quickstart  _should_ be as simple as installing docker and running `docker-compose up`. BUT, we are not there yet and I think this is a good add to merge soon.

The solution I would like best (and what I think meets most sentiments):
- [ ] Move Step 3 to the final Step
- [ ] Include a note at the end of Step 2 that reads(ish):

> Great! You've made it this far. Steps 3-6 get pretty weedsy into code. If you are not a developer and would still love to contribute, hop down to [Step 7](#whooop-this-isnt-a-real-link)

Then in the future Steps 3-6 will be increasingly non-dev friendly. Thoughts?

@iamtrask What are your goals for this document?

2017-08-18 23:04 UTC, cereallarceny commented
I think that's a great idea @kevinahuber - seems like a good balance.  I'll implement this now.

2017-08-19 14:56 UTC, kevinahuber approved these changes
👍

2017-08-19 17:44 UTC, iamtrask approved these changes
beautiful!

2017-08-19 17:44 UTC, merged